In [10]:
import pandas as pd

# Read a .csv froma URL with Pandas
Target website: https://football-data.co.uk/data.php

In [3]:
# Reading 1 csv file from the website
df_premier24_25 = pd.read_csv('https://football-data.co.uk/mmz4281/2425/E0.csv')

In [4]:
# Showing dataframe
df_premier24_25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

In [12]:
# Rename columns
df_premier24_25.rename(columns={'FTHG':'HomeGoals',
                                'FTAG':'AwayGoals'}, inplace=True)

In [11]:
# Show dataframe
df_premier24_25

,Div,Date,Time,HomeTeam,AwayTeam,HomeGoals,AwayGoals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,0,...,2.00,1.85,2.01,1.90,2.01,1.95,1.95,1.91,1.93,2.05
376,E0,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,0,...,1.80,2.05,1.86,2.08,1.86,2.08,1.81,2.05,1.86,2.14
377,E0,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,1,...,2.03,1.83,2.04,1.87,2.07,1.87,2.03,1.83,2.06,1.89
378,E0,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,0,...,1.95,1.90,2.00,1.93,2.01,1.93,1.95,1.89,2.06,1.93
379,E0,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,1,...,1.85,2.00,1.90,2.03,1.90,2.05,1.85,1.97,1.89,2.10

# Read a .csv from a URL with Pandas
Link: root, season, league

In [14]:
# Link structure
"https://football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

'https://football-data.co.uk/mmz4281/2122/E0.csv'

In [11]:
# Create root variable
root = "https://football-data.co.uk/mmz4281/"

### Multiple Leagues

-https://football-data.co.uk/mmz4281/2425/E0.csv

-https://football-data.co.uk/mmz4281/2425/E1.csv

-https://football-data.co.uk/mmz4281/2425/E2.csv

-https://football-data.co.uk/mmz4281/2425/E3.csv

-https://football-data.co.uk/mmz4281/2425/EC.csv

In [18]:
# Creating the list of leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []

# Looping through leagues, read multiple csv and append them into a list
for league in leagues:
    df = pd.read_csv(root+ '2425' + '/' + league + '.csv', encoding='unicode_escape')
    frames.append(df)

In [19]:
# length of frames
len(frames)

5

In [21]:
# show 1st, 2nd, and 3rd element
frames[1]

,ï»¿Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E1,09/08/2024,20:00,Blackburn,Derby,4,2,H,1,0,...,1.85,2.05,1.85,2.06,1.97,2.10,1.85,1.99,1.88,2.11
1,E1,09/08/2024,20:00,Preston,Sheffield United,0,2,A,0,1,...,1.92,1.98,1.93,1.98,1.97,1.99,1.90,1.94,1.94,2.04
2,E1,10/08/2024,12:30,Cardiff,Sunderland,0,2,A,0,1,...,2.11,1.79,2.13,1.80,2.13,1.81,2.09,1.79,2.18,1.83
3,E1,10/08/2024,12:30,Hull,Bristol City,1,1,D,0,0,...,1.99,1.91,2.00,1.91,2.04,1.91,1.99,1.87,2.03,1.96
4,E1,10/08/2024,12:30,Leeds,Portsmouth,3,3,D,1,2,...,1.92,1.98,1.93,1.95,2.00,1.98,1.94,1.89,2.00,1.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E1,03/05/2025,12:30,Sheffield United,Blackburn,1,1,D,0,0,...,1.89,2.01,1.90,2.01,1.91,2.11,1.84,2.04,1.89,2.10
548,E1,03/05/2025,12:30,Sunderland,QPR,0,1,A,0,1,...,2.01,1.89,2.04,1.88,2.19,1.89,2.04,1.81,2.16,1.82
549,E1,03/05/2025,12:30,Swansea,Oxford,3,3,D,1,1,...,2.02,1.88,2.03,1.88,2.08,1.89,2.00,1.85,2.09,1.89
550,E1,03/05/2025,12:30,Watford,Sheffield Weds,1,1,D,1,1,...,1.85,2.00,1.86,2.05,2.00,2.05,1.92,1.94,2.00,1.99
551,E1,03/05/2025,12:30,West Brom,Luton,5,3,H,3,1,...,1.91,1.99,1.89,2.01,1.97,2.01,1.87,1.94,1.92,2.05

# Multiple Seasons

In [23]:
# Creating the list of leagues
leagues = ['E0', 'E1', 'E2']
frames = []

# Looping through the range of seasons and insert a new column
for league in leagues:
    for season in range(20, 25):
        df = pd.read_csv(root + (str(season) + str(season+1)) + '/' + league + '.csv')
        df.insert(1, 'Season', season)
        frames.append(df)

In [24]:
# Total frames (5 seasons x 3 leagues)
len(frames)

15

In [28]:
# Show 1st, and last element (new season column was created)
frames[12]

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E2,22,30/07/2022,15:00,Accrington,Charlton,2,2,D,0,...,1.92,0.00,2.05,1.75,2.08,1.83,2.16,1.83,2.06,1.77
1,E2,22,30/07/2022,15:00,Bristol Rvs,Forest Green,1,2,A,0,...,1.75,-0.25,2.10,1.77,2.09,1.82,2.13,1.82,2.07,1.76
2,E2,22,30/07/2022,15:00,Cambridge,Milton Keynes Dons,1,0,H,1,...,1.61,0.25,1.70,2.10,1.76,2.14,1.86,2.14,1.78,2.05
3,E2,22,30/07/2022,15:00,Cheltenham,Peterboro,2,3,A,2,...,2.04,0.25,1.93,1.93,1.98,1.90,1.98,1.99,1.89,1.92
4,E2,22,30/07/2022,15:00,Derby,Oxford,1,0,H,0,...,1.81,-0.25,1.75,2.05,1.79,2.10,1.86,2.14,1.79,2.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,22,07/05/2023,12:00,Lincoln,Shrewsbury,1,0,H,0,...,1.81,-0.50,1.95,1.90,1.98,1.87,2.00,1.94,1.95,1.84
548,E2,22,07/05/2023,12:00,Oxford,Accrington,1,2,A,1,...,2.11,-1.25,1.90,1.95,1.94,1.90,1.96,2.02,1.90,1.90
549,E2,22,07/05/2023,12:00,Port Vale,Plymouth,1,3,A,1,...,2.18,0.75,1.95,1.90,1.94,1.91,2.04,1.94,1.96,1.85
550,E2,22,07/05/2023,12:00,Portsmouth,Wycombe,2,2,D,1,...,2.06,-0.25,1.80,2.00,1.90,1.95,1.90,2.06,1.83,1.95
551,E2,22,07/05/2023,12:00,Sheffield Weds,Derby,1,0,H,1,...,1.81,0.00,1.98,1.88,1.97,1.88,2.05,1.90,1.92,1.86

# Organize All The Data in a Dictonary

In [3]:
# Create a dictionary with the original name of the league as the key
dict_countries = {
    'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
    'German Bundesliga':'D1',
    'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3'
}

In [4]:
# Get a dictionary element
dict_countries['Spanish La Liga']

'SP1'

In [6]:
for league in dict_countries:
    print(dict_countries[league])

SP1
SP2
D1
E0
E2
E3

In [12]:
dict_historical_data = {}


# Looping through the range of seasons and insert a new column
for league in dict_countries:
    frames = []
    for season in range(20, 25):
        df = pd.read_csv(root + (str(season) + str(season+1)) + '/' + dict_countries[league] + '.csv')
        df.insert(1, 'Season', season)
        frames.append(df)
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [15]:
# Show dataframe inside dict_historical_data
dict_historical_data['English Premier League']

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,1XBCH,1XBCD,1XBCA,BFECH,BFECD,BFECA,BFEC>2.5,BFEC<2.5,BFECAHH,BFECAHA
0,E0,20,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,20,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,20,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,20,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,20,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24,25/05/2025,16:00,Newcastle,Everton,0,1,A,0,...,1.30,6.11,10.20,1.27,7.0,13.00,1.50,2.94,1.93,2.05
376,E0,24,25/05/2025,16:00,Nott'm Forest,Chelsea,0,1,A,0,...,3.50,3.86,2.06,3.55,3.9,2.14,1.76,2.28,1.86,2.14
377,E0,24,25/05/2025,16:00,Southampton,Arsenal,1,2,A,0,...,12.20,6.11,1.28,13.00,6.8,1.28,1.45,3.15,2.06,1.89
378,E0,24,25/05/2025,16:00,Tottenham,Brighton,1,4,A,1,...,3.63,4.12,1.95,3.95,4.2,1.93,1.51,2.92,2.06,1.93
379,E0,24,25/05/2025,16:00,Wolves,Brentford,1,1,D,0,...,2.98,3.80,2.31,3.05,3.8,2.42,1.54,2.78,1.89,2.10